### PR TITLE
TRAINING-16 Add logo to website

### PR DESCRIPTION
**Pull request by brucearctor**
I think this addresses the size issue; but don't have a good way of testing the website, so am not certain.  Tried for a quick fix.  Maybe works?  Alternately, happy to try this out some more with detailed attention, and/or wait for svg.  Either way, I should probably rebase, so that the large image size doesn't stick with us in repo pull/clones?

### CODE REVIEW

**Comment by brucearctor** [comment]
this was done hastily, so perhaps better to wait?

**Comment by lfrancke** [comment]
Daniel sent over an SVG version in Slack. If you're fine with that I'd close this PR and submit a new one with that version

**Comment by justinmclean** [comment]
For a simple obvious improvement like this I'd just go ahead and do it, (JFDI! is often used at Apache) it's only going to improve things.

**Comment by lfrancke** [comment]
I don't want to discourage contribution by Bruce so if he wants to do it I'd be fine as well and we're in no hurry.

**Comment by justinmclean** [comment]
I guess there's not a huge rush,  but our site is looking a bit ugly currenlty.

**Comment by dspavlov** [comment]
I would like to say +1 to Lars proposal, I also ok with waiting couple days. Addressing my previous experience as a community manager, I must admit that is always very easy to do something wrong and lost a contributor, and it is not easy to inspire/encourage someone to volunteer.

**Comment by brucearctor** [comment]
Was away traveling -- just made the changes locally; will open new PR with the SVG.

**Pull request closed without merging**
