### PR TITLE
Minor template cleanup

### PR DESCRIPTION
**Pull request by lfrancke**
Please see #13 for more context.

This is a new version of the PR that mostly fixes the typo in the directory name "templte" -> "template" and a few other minor things.

### CODE REVIEW

**Comment by lfrancke** [comment]
@chrisdutz Will this require a Jenkins change? If so: I don't have access to Jenkins. Could you do that?

**Comment by justinmclean** [comment]
+1 for me

**Comment by lfrancke** [comment]
I'll hold off on merging until someone with Jenkins privileges can attend to it.

**Comment by chrisdutz** [comment]
Yeah ... I'll just merge that and instantly update Jenkins.

**Pull request merged**
