### PR TITLE
Training-34: Apache Pulsar

### PR DESCRIPTION
**Pull request by greatgautam**
Presentation for Apache Pulsar

### CODE REVIEW

**Comment by greatgautam** [comment]
Please review.

**Review by chrisdutz — APPROVED** [review]
Looking good to me

**Comment by justinmclean** [comment]
You might want to add a bit of meta data to describe the talk, something like:
:description: 30 minutes talk on Pulsar
:keywords: Pulsar
:talk: Introduction t Pulsar

**Review by justinmclean — APPROVED** [review]

**Comment by greatgautam** [comment]
> You might want to add a bit of meta data to describe the talk, something like:
> :description: 30 minutes talk on Pulsar
> :keywords: Pulsar
> :talk: Introduction t Pulsar

Sure, I have added some meta data in the deck.

**Comment by brahmareddybattula** [comment]
Nice work…..Not sure ,worth to mention benchmarking with Kafka

**Pull request merged**
