### PR TITLE
Add Review Options for Contribution

### PR DESCRIPTION
**Pull request by greatgautam**
This is a change to add review model for content contribution. Please review.

### CODE REVIEW

**Comment by greatgautam** [comment]
How can i merge this PR? Can I get write access to merge it please?

**Comment by dspavlov** [comment]
@greatgautam committers can merge code into master. I've merged this change since there were no objections and 2 LGTMs. You can reach committers on a list or here on GitHub.

**Comment by greatgautam** [comment]
Hi,
I have created the PR and it is merged now. I'd like to update the status
of JIRA-23. Please let me know how can I assign a JIRA to myself?

thanks,
Gautam

**Comment by dspavlov** [comment]
Hi, this is a good question. To be able to change state of JIRA tickets we need to do 2 things
- change project schema in JIRA (I was eager to do it, it is on my side)
- add you as a contributor.

Would you mind giving me some time to prepare an INFRA request?

**Pull request merged**
