### PR TITLE
Updated the template to the most recent versions and added some additional features and examples

### PR DESCRIPTION
**Pull request by chrisdutz**
- Updated asciidoctorj to 2.1.0
- Updated asciidoctor diagrams to 1.5.18
- Updated revealjs to 3.8.0
- Added CSS styles for two column slides
- Added CSS styles for some additional simple colors
- Added example on how to use the two-column feature
- Added example on how to use fontawesome icons (also using the color styles)

### CODE REVIEW

**Comment by chrisdutz** [comment]
Ah ... and I moved that one file install-deps-centos.sh into the correct directory.

**Comment by lfrancke** [comment]
You are still discussing with Justin on the mailing list or is this ready to be committed?

**Comment by chrisdutz** [comment]
Didn't know I was discussing anything with Justin on the list ... from my side it's fine.

**Comment by lfrancke** [comment]
Oh, I misread. I thought you were discussing two different approaches to the multi-column thing. I didn't follow closely

**Comment by justinmclean** [comment]
There are many ways to do this, all are fine as far as I'm concerned. I just provided that example as it maybe be useful.

**Comment by soenkeliebau** [comment]
LGTM

**Pull request merged**
