### PR TITLE
Minor cleanup of the presentation template

### PR DESCRIPTION
**Pull request by lfrancke**
- Fixed typo in directory name templte -> template
- Fixed a few things in the pom, e.g. warnings Maven was throwing

Signed-off-by: Lars Francke <lars.francke@gmail.com>

### CODE REVIEW

**Comment by justinmclean** [comment]
Looks fine to me except for the conflict.

**Comment by lfrancke** [comment]
I have no idea what's going on here.
All I did (or thought I did) was rebase to latest master and resolve merge conflict but now I get all those commits from Justin again. And it looks like this PR even includes the comment from my review for Justins PR. I currently have no idea how to fix this - please don't merge.

**Comment by lfrancke** [comment]
I tried following this https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch but it failed because of Github UI issues so I'll resubmit the PR.

**Comment by justinmclean** [comment]
Hi,

> I have no idea what's going on here.
> All I did (or thought I did) was rebase to latest master and resolve merge conflict but now I get all those commits from Justin again. And it looks like this PR even includes the comment from my review for Justins PR. I currently have no idea how to fix this - please don't merge

It may be that https://gitbox.apache.org/repos/asf/incubator-training.git is out of sync with https://github.com/apache/incubator-training.git. I think Chris run into this a few times on the PLC4X project.

There’s a sync git repos at Apache self-selve [1] I’ll try that.

Thanks,
Justin

1. https://infra.apache.org

**Comment by lfrancke** [comment]
You might be right, let's see.
I resubmitted my same branch as a new PR though and now everything looks good. The StackOverflow link I posted also says that this could be a limitation of the Github interface but I'm not sure.

**Pull request closed without merging**
